### PR TITLE
Add 'insertInforming' function

### PR DESCRIPTION
**Pull request by k-bx**
Add 'insertInforming' function

### CODE REVIEW

**Comment by k-bx** [comment]
@chowells79 hi! Just wanted to ping you on this once again. Please merge and make a release so I can stop supporting my own fork :)

**Comment by chowells79** [comment]
Remind me again if I don't have this done by monday, please.

**Comment by k-bx** [comment]
@chowells79 hi! Just reminding about myself.

**Comment by chowells79** [comment]
I am working on this now, but I can't just take your pull request - I'm going to abandon the current master branch. It had a lot of experiments that didn't work.

**Comment by chowells79** [comment]
Releasing this is currently blocked on recovering my hackage password, which is proving to be a challenge.  There will be a release as soon as that happens, though.

**Comment by k-bx** [comment]
Perfect, thanks!

**Comment by chowells79** [comment]
LRUCache 1.2.0.0 has been published. Let me know if anything's broken.

**Comment by k-bx** [comment]
By incident just updated hackage page and saw the release. Thanks, will switch to it from my fork and check everything tomorrow!

**Pull request merged**
